apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-marcos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-marcos
  template:
    metadata:
      labels:
        app: deploy-marcos
    spec:
      containers:
      - name: deploy-marcos
        image: deploy-marcos
        ports:
        - containerPort: 8080
