apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml

namespace: arcocd

images:
- name: deploy-marcos
  newName: marcosaureliofarias/deploy
  newTag: v1