apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: marcos

images:
- name: deploy-marcos
  newName: marcosaureliofarias/deploy
  newTag: 366447a53d730e6ddf93d923140552f745dc4db5
