apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- nodeport.yml

namespace: marcos

images:
- name: deploy-marcos
  newName: marcosaureliofarias/deploy
  newTag: 92274b32cc388eda0c788ccc6d3201affec28f25
