apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- loadBalancer.yml

namespace: marcos

images:
- name: deploy-marcos
  newName: marcosaureliofarias/deploy
  newTag: c3668e6cc945a1de475a0603c50ba011cb2bf66b
