apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- loadBalancer.yml

namespace: marcos

images:
- name: deploy-marcos
  newName: marcosaureliofarias/deploy
  newTag: 201c2c6e02d33aed9beeb697d382ac43caa2bfd7
